### ISSUE TITLE
LayerUpdate feature that does not try to merge tiles

### ISSUE THREAD

**Issue by lossyrob** [locationtech/geotrellis#2327] opened 2017-08-10 16:25 UTC
If the user knows there are no tiles to merge, the LayerUpdater shouldn't need to read the old tiles. This speeds up things a lot. For instance, I did this in a recent ingest:

```scala
            val lid = LayerId(layerName, z)
            if(as.layerExists(lid)) {
              // Some manual updating to speed things up
              // Taken from S3LayerUpdater
              val LayerAttributes(header, metadata, keyIndex, writerSchema) =
                as.readLayerAttributes[S3LayerHeader, TileLayerMetadata[SpaceTimeKey], SpaceTimeKey](lid)
              val prefix = header.key
              val bucket = header.bucket
              val maxWidth = Index.digits(keyIndex.toIndex(keyIndex.keyBounds.maxKey))
              val keyPath = (key: SpaceTimeKey) => makePath(prefix, Index.encode(keyIndex.toIndex(key), maxWidth))
              val updatedMetadata = metadata.merge(layer.metadata)
              val codec  = KeyValueRecordCodec[SpaceTimeKey, MultibandTile]
              val schema = codec.schema
              as.writeLayerAttributes(lid, header, updatedMetadata, keyIndex, schema)
              S3RDDWriter.write(layer, bucket, keyPath)
            } else {
              writer.write(lid, layer, keyIndex)
            }

```

**Comment by echeipesh** [comment] 2017-08-31 20:23
Overall problem LayerUpdater does not size partitions when reading tiles from already existing layer:
https://github.com/locationtech/geotrellis/blob/master/spark/src/main/scala/geotrellis/spark/io/file/FileLayerUpdater.scala#L75

When number of tiles returned are too large to be fit into default number of partitions (2-8 typically) this is will fail. A good way to reproduce this problem is to use a layer updater in https://github.com/geotrellis/geotrellis-landsat-tutorial
example: https://github.com/echeipesh/geotrellis-landsat-tutorial/tree/layer-updater

### Proposed Solution
Overall the strategy of using LayerReader to fetch the tiles is suboptimal because it requires both a stage of query preparation and then RDD level shuffle to line up the tiles to be updated.


What we need is a `_RDDUpdater.scala` that similar to the writer groups the records by their z-index, reads the existing block, applies the merge function to resolve the duplicates and writes the updated record.

Possible parameters here:
- `(Vector[V], Vector[V] => Vector[V])` merge function
- alwaysOverwrite flag

**Comment by echeipesh** [comment] 2017-10-09 14:32
Resolved by: https://github.com/locationtech/geotrellis/pull/2396

**Closed by echeipesh** 2017-10-09 14:32 UTC
