### ISSUE TITLE
MulitbandTiles Cannot Perform Local Operations

### ISSUE THREAD

**Issue by jbouffard** [locationtech/geotrellis#2162] opened 2017-04-24 20:21 UTC
As it currently stands `MultibandTile`s cannot perform any focal operations in GeoTrellis. Whereas `Tile`s can.

For example:
```scala

// this will not work
val plusOne = multibandTile + 1

// this is the workaround
val plusOne = multibandTile.bands.map { x => x + 1}
```

While the work around isn't difficult, it might be worth implementing these operations for `MultibandTile`s regardless.

**Comment by echeipesh** [comment] 2017-09-07 09:24
Duplicate of https://github.com/locationtech/geotrellis/issues/1789

**Closed by echeipesh** 2017-09-07 09:24 UTC
