### ISSUE TITLE
RGBA tiles produced by MultibandColorMethods.color are not suitable for use with renderJpg, but no ARGB alternative exists

### ISSUE THREAD

**Issue by natonic77** [locationtech/geotrellis#3151] opened 2019-11-11 18:10 UTC
ImageIO BufferedImage.TYPE_INT_RGB (and TYPE_INT_ARGB) assume R, G, and B components are in bits 0-23, and alpha is in 24-31 (and is ignored in TYPE_INT_RGB): https://stackoverflow.com/questions/6001211/format-of-type-int-rgb-and-type-int-argb.

It would be helpful to offer a version of color that provides an ARGB so that it can be used with renderJpg.  Could use almost identical logic as is found here: https://github.com/locationtech/geotrellis/blob/master/raster/src/main/scala/geotrellis/raster/render/ColorMethods.scala, but adjust bitshift order to put alpha in the highest 8 bits.

Not a problem or a need for renderPng, because it doesn't appear to use ImageIO for rendering.

Additional, somewhat related issue is that the ColorMethods.toBufferedImage call made in the JpgEncoder is also not properly populating the A, R, or G bands when writing a Byte raster (toBufferedImage assumes that raster Cells are always ARGB, but for a Byte raster only the first byte is populated - so the output ends up being "bluescale").

**Comment by pomadchin** [comment] 2020-08-14 23:43
Duplicate of https://github.com/locationtech/geotrellis/issues/3203 and closed in https://github.com/locationtech/geotrellis/pull/3278

**Closed by pomadchin** 2020-08-14 23:43 UTC
Labels: bug
