### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException when trying to get value from Tile

### ISSUE THREAD

**Issue by Charmatzis** [locationtech/geotrellis#2525] opened 2017-12-18 08:54 UTC
If you try and run the above code you will see that it returns `java.lang.ArrayIndexOutOfBoundsException`

```scala
import geotrellis.vector._
import geotrellis.raster._
import geotrellis.proj4.WebMercator
import geotrellis.spark.tiling._
import geotrellis.spark._
import geotrellis.raster.rasterize._
import org.apache.spark.sql.SparkSession
import geotrellis.raster.rasterize.Rasterizer

object TestRasterazerFaliure extends App {

  val _spark = SparkSession
    .builder()
    .master("local[*]")
    .appName("Rasterazer")
    .getOrCreate()

  import _spark.implicits._

  val conf = _spark.sparkContext.getConf
  implicit val sc = _spark.sparkContext

  implicit val _sql = _spark.sqlContext



  val p = Point(17532819.799940586, 5425368.153816739)
  val tileSize = 512
  val zoom = 4

  val layout = ZoomedLayoutScheme(WebMercator, tileSize).levelForZoom(zoom).layout

  val pointRDD = sc.parallelize(Array(p))

  val result = pointRDD.rasterize(1, IntConstantNoDataCellType, layout)

  result.collect()


  println("the end")

}
```

Even thought the collect is succeeded, the x value of the SpatialKey is -1 here 
https://github.com/locationtech/geotrellis/blob/04a60d0ee8734602aaa2635046107a474d5109cd/spark/src/main/scala/geotrellis/spark/rasterize/RasterizeRDD.scala#L71

**Comment by pomadchin** [comment] 2017-12-18 08:58
Hey @Charmatzis these functions work like this by design. For sure you can't access (-1, 426) value. Can you prepare an original example from our gitter channel?

**Comment by Charmatzis** [comment] 2017-12-18 12:09
I have updated the  description.

**Comment by jpolchlo** [comment] 2017-12-21 15:17
@Charmatzis I'm fairly certain you're experiencing your very first encounter with the numerical precision woes that can often plague vector code.  Observe:

```scala
scala> val p = Point(17532819.799940586, 5425368.153816739)
p: geotrellis.vector.Point = POINT (17532819.799940586 5425368.153816739)

scala> val layout = ZoomedLayoutScheme(WebMercator, 512).levelForZoom(4).layout
layout: geotrellis.spark.tiling.LayoutDefinition = GridExtent(Extent(-2.0037508342789244E7, -2.0037508342789244E7, 2.0037508342789244E7, 2.0037508342789244E7),4891.96981025128,4891.96981025128)

scala> val key = layout.mapTransform(p)
key: geotrellis.spark.SpatialKey = SpatialKey(15,5)

scala> val ex = layout.mapTransform(key)
ex: geotrellis.vector.Extent = Extent(1.753281979994059E7, 5009377.085697312, 2.0037508342789244E7, 7514065.628545966)

scala> ex.contains(p)
res8: Boolean = false

scala> ex.covers(p)
res9: Boolean = false

scala> math.abs(res7.xmin - p.x)
res11: Double = 3.725290298461914E-9
```

The story is: your point is very close to a key boundary that appears at level 4 (so you won't see it at lower zoom levels).  `MapKeyTransform` identifies your point as being in `SpatialKey(15, 5)`, but it's actually in `SpatialKey(14, 5)`.  It's just so close that numerical error leads to an incorrect inclusion test.  When we actually do the math to determine the pixel location, the error emerges.

You may consider using the fixed precision JTS model for your geometry.  Some documentation on how to do that is [here](http://geotrellis.readthedocs.io/en/latest/guide/vectors.html#numerical-precision-and-topology-exceptions).  In your case, a scale factor around 1e-8 might help.  It may be an unsatisfying solution if you have a lot of points very close to one another, since they will not be distinct after cutting down their precision.  But, hey!  At least your code will run.

The alternative is to use numerically robust inclusion tests that will really slow you down.  That's probably a conversation we should have on our end.

**Comment by Charmatzis** [comment] 2018-01-08 09:33
@jpolchlo thx for the answer. 
Now the good stuff.... 
If I use the `application.conf`
and insert 

```
geotrellis.jts.precision.type="fixed"
geotrellis.jts.precision.scale=0
```
Which means since I am in WebMercator the precision in in meters, which is OK for my project,
All the points that I want to rasterize are transformed their geometries to precision meters , because the it passes through here
https://github.com/locationtech/geotrellis/blob/master/vector/src/main/scala/geotrellis/vector/Point.scala#L25 

and the `factory` is taking care this.


But..... when I try to rasterize, these points are transformed into Geometries and the Geometry doesn't include any GeometryFactory.
https://github.com/locationtech/geotrellis/blob/master/vector/src/main/scala/geotrellis/vector/Geometry.scala

**Comment by jpolchlo** [comment] 2018-01-09 17:46
Hi, @Charmatzis.  Could you check out #2538 and see if it fixes your problem?  You'll need to keep the changes to your `application.conf` mentioned in your last comment.

**Comment by jpolchlo** [comment] 2018-01-09 17:48
Actually, you need to change `geotrellis.jts.precision.scale` to 1.  A value of 0 will reduce all your points to the origin.

**Comment by pomadchin** [comment] 2020-08-15 00:06
I'll close this PR since there is no interest in it anymore. @Charmatzis feel free to reopen if it is still a problem.

**Closed by pomadchin** 2020-08-15 00:06 UTC
