### ISSUE TITLE
Attempting to save to S3 fails with com.amazonaws.AmazonClientException: Unable to load AWS credentials from any provider in the chain

### ISSUE THREAD

**Issue by hriundel** [locationtech/geotrellis#2236] opened 2017-06-13 04:53 UTC
I'm trying to save my generated images to s3 following example here: https://github.com/geotrellis/geotrellis-landsat-tutorial/blob/master/src/main/scala/tutorial/IngestImage.scala but instead of using `FileAttributeStore` I'm using `S3AttributeStore`. My code looks like this
```
// ..
val attributeStore = S3AttributeStore(bucket, path)  
val writer = S3LayerWriter(attributeStore)
Pyramid.upLevels(reprojected, layoutScheme, zoom, Bilinear) { (rdd, z) =>
      val layerId = LayerId("landsat", z)

      //val keyToPath = SaveToS3.spatialKeyToPath(layerId, pathTemplate)
      //val byteRdd = rdd.map { case (key, tile) => (key, tile.renderPng().bytes) }
      //SaveToS3(byteRdd, keyToPath)

      writer.write(layerId, rdd, ZCurveKeyIndexMethod)
      }
  }
// ..

```
but it fails with `com.amazonaws.AmazonClientException: Unable to load AWS credentials from any provider in the chain`. It will also fail with the same exception if I uncomment three lines above and try to call `SaveToS3` directly.

I'm using a multi-node spark cluster and I verified that my credentials are there on every node. I even added `~/.aws/credentials` file on every node just to be sure. 

Also, if I try to instantiate `S3Client.DEFAULT` in the same scope as my code snippet above and attempt to interact with my s3 bucket, it works ok, so I'm reasonably sure it's not the case of undefined environment variables.

**Comment by pomadchin** [comment] 2017-06-13 04:57
Thx for your report! Can you add how and where do you create S3Client.DEFAULT?

**Comment by hriundel** [comment] 2017-06-13 05:11
Yea, if I do:
```
val s3Obj = S3Client.DEFAULT.getObject(bucketName, keyName)
print(s"s3Obj")

val attributeStore = S3AttributeStore(bucket, path)
// ...
```

it works ok

**Comment by pomadchin** [comment] 2017-06-13 06:25
I could not reproduce it: 

```scala
package geotrellis.chatta

import geotrellis.raster._
import geotrellis.raster.resample._
import geotrellis.proj4._

import geotrellis.spark._
import geotrellis.spark.io._
import geotrellis.spark.io.s3._
import geotrellis.spark.io.hadoop._
import geotrellis.spark.io.index._
import geotrellis.spark.pyramid._
import geotrellis.spark.tiling._

import geotrellis.vector._

import org.apache.spark._
import org.apache.spark.rdd._

import scala.io.StdIn

object TestIngest {
  val inputPath = "file:///data/arg_wm/DevelopedLand.tiff"
  val (bucket, prefix) = "geotrellis-test" -> "daunnc/chatta"

  def main(args: Array[String]): Unit = {
    // Setup Spark to use Kryo serializer.
    val conf =
      new SparkConf()
        .setMaster("local[*]")
        .setAppName("Spark Tiler")
        .set("spark.serializer", "org.apache.spark.serializer.KryoSerializer")
        .set("spark.kryo.registrator", "geotrellis.spark.io.kryo.KryoRegistrator")

    val sc = new SparkContext(conf)
    try {
      run(sc)
      // Pause to wait to close the spark context,
      // so that you can check out the UI at http://localhost:4040
      println("Hit enter to exit.")
      StdIn.readLine()
    } finally {
      sc.stop()
    }
  }

  def fullPath(path: String) = new java.io.File(path).getAbsolutePath

  def run(implicit sc: SparkContext) = {
    // Read the geotiff in as a single image RDD,
    // using a method implicitly added to SparkContext by
    // an implicit class available via the
    // "import geotrellis.spark.io.hadoop._ " statement.
    val inputRdd: RDD[(ProjectedExtent, Tile)] =
    sc.hadoopGeoTiffRDD(inputPath)

    // Use the "TileLayerMetadata.fromRdd" call to find the zoom
    // level that the closest match to the resolution of our source image,
    // and derive information such as the full bounding box and data type.
    val (_, rasterMetaData) =
    TileLayerMetadata.fromRdd(inputRdd, FloatingLayoutScheme(512))

    // Use the Tiler to cut our tiles into tiles that are index to a floating layout scheme.
    // We'll repartition it so that there are more partitions to work with, since spark
    // likes to work with more, smaller partitions (to a point) over few and large partitions.
    val tiled: RDD[(SpatialKey, Tile)] =
    inputRdd
      .tileToLayout(rasterMetaData.cellType, rasterMetaData.layout, Bilinear)
      .repartition(100)

    // We'll be tiling the images using a zoomed layout scheme
    // in the web mercator format (which fits the slippy map tile specification).
    // We'll be creating 256 x 256 tiles.
    val layoutScheme = ZoomedLayoutScheme(WebMercator, tileSize = 256)

    // We need to reproject the tiles to WebMercator
    val (zoom, reprojected): (Int, RDD[(SpatialKey, Tile)] with Metadata[TileLayerMetadata[SpatialKey]]) =
      TileLayerRDD(tiled, rasterMetaData)
        .reproject(WebMercator, layoutScheme, Bilinear)

    // Create the attributes store that will tell us information about our catalog.
    val attributeStore = S3AttributeStore(bucket, prefix)

    // Create the writer that we will use to store the tiles in the local catalog.
    val writer = S3LayerWriter(attributeStore)

    // Pyramiding up the zoom levels, write our tiles out to the local file system.
    Pyramid.upLevels(reprojected, layoutScheme, zoom, Bilinear) { (rdd, z) =>
      val layerId = LayerId("landsat", z)
      // If the layer exists already, delete it out before writing
      if(attributeStore.layerExists(layerId)) {
        new S3LayerManager(attributeStore).delete(layerId)
      }
      writer.write(layerId, rdd, ZCurveKeyIndexMethod)
    }
  }
}
```

**Comment by hriundel** [comment] 2017-06-13 15:49
Ok, so I ran the ingest in local mode on every node, and it finished successfully.
Then, from your suggestion, I checked my aws-sdk dependencies and turns out my `spark-defaults.conf` had the following lines:
```
# spark-defaults.conf

spark.hadoop.fs.s3a.impl org.apache.hadoop.fs.s3a.S3AFileSystem
spark.executor.extraClassPath /usr/local/spark/lib/aws-java-sdk-1.7.4.jar:/usr/local/spark/lib/hadoop-aws-2.7.2.jar
spark.driver.extraClassPath /usr/local/spark/lib/aws-java-sdk-1.7.4.jar:/usr/local/spark/lib/hadoop-aws-2.7.2.jar

```

So, when running in cluster mode, it was pulling 1.7.4 version of aws sdk. Besides a different way of instantiating `DefaultAWSCredentialsProviderChain`, the older version didn't even check for credentials in `~/.aws/credentials`. 

After changing downloading updated jar (1.11.92 - the same as geotrellis 1.1.0-RC6 uses), everything works. Now I'm getting some warning about `java.util.ServiceConfigurationError: org.apache.hadoop.fs.FileSystem: Provider org.apache.hadoop.fs.s3a.S3AFileSystem could not be instantiated` but at least the rest of the job seems to finish successfully.

Thanks!

**Comment by pomadchin** [comment] 2017-06-13 17:15
@hriundel glad that it worked :tada:, btw, I believe your next issue can be resolved by adding `hadoop-aws` into your project deps.

**Closed** 2017-06-13 17:19 UTC
Labels: bug
