### ISSUE TITLE
Reading then writing vector tile features drops some

### ISSUE THREAD

**Issue by mojodna** [locationtech/geotrellis#2926] opened 2019-05-18 01:29 UTC
When reading geometries from MVTs, projected coordinates correspond to the top left of the tile "pixel":

https://github.com/locationtech/geotrellis/blob/0683298e59517fa5f25cfea984221da2eaa792bd/vectortile/src/main/scala/geotrellis/vectortile/internal/package.scala#L123-L128

This has the effect of shifting (and dropping) features that are read from MVTs and subsequently written to new ones. This is more noticeable with a small `tileWidth`, e.g. 128 (used when bucketing points).

Points on the top or left edge will be assigned and y or x value corresponding to the extent. Somewhere along the way, features that fail an `extent.contains` test will be dropped. Features that pass will have been shifted slightly up and to the left.

I _think_ that the right fix for this is to translate geometries read from MVTs by `(resolution / 2, resolution / -2)`, generating projected coordinates in the center of the tile "pixel".

**Comment by jbouffard** [comment] 2019-07-22 12:49
If I'm understand this issue correctly, the problem is that we sometimes drop and/or shift points when converting from `VectorTile` grid space to a `CRS` point and back. This can be resolved by translating the geometry's point(s) to the center of the cell instead of the edge. Is that correct?

@mojodna @jpolchlo Do you guys have an example of where this happens? I've been trying to come up with a test case, but so far everything seems to work okay.

**Comment by mojodna** [comment] 2019-07-23 02:59
Correct. Translating when reading.

This is where I was encountering (and working around) it:

https://github.com/azavea/osmesa/blob/62b598e4435ab56a9e4997791dae4dd043d13c4f/src/analytics/src/main/scala/osmesa/analytics/EditHistogram.scala#L96-L101

**Comment by jbouffard** [comment] 2019-07-23 12:35
@mojodna Thank you! I'm currently resolving this issue in GT right now, but I'm unable to recreate this behavior for a unit test. Do you know of a simple example of when this shifting occurs?

**Comment by mojodna** [comment] 2019-07-24 00:15
Not immediately. It was happening to me when extracting coordinates for individual raster cells and writing them into an MVT (with a non-standard `cellSize` of 256 or 512). Location-wise, I was seeing it both in Venezuela and Eastern Europe around zoom 8, but that may just have been where the MVTs had been updated (and had their coordinates invalidated).

**Comment by mojodna** [comment] 2019-07-24 15:58
Ok, I have an actual test case that isolates the problem to serialization / deserialization (`VectorTile.toBytes` / `VectorTile.fromBytes`):

```scala
  it("round trips coordinates correctly") {
    val p = Point(-61.3422, 10.4068)
    val reprojected = p.reproject(LatLng, WebMercator)
    val f = Feature(reprojected, Map.empty[String, Value])
    val tileExtent = SpatialKey(168, 241).extent(ZoomedLayoutScheme(WebMercator).levelForZoom(9).layout)

    val layer = StrictLayer(
      name = "test",
      tileWidth = 128,
      version = 2,
      tileExtent = tileExtent,
      points = Seq(f),
      multiPoints = Seq.empty,
      lines = Seq.empty,
      multiLines = Seq.empty,
      polygons = Seq.empty,
      multiPolygons = Seq.empty
    )

    val vt = VectorTile(Map("test" -> layer), tileExtent)

    // ~success, with floating point variation
    layer.features.head.mapGeom(_.reproject(WebMercator, LatLng)).geom should equal(p)

    val vt2 = VectorTile.fromBytes(vt.toBytes, tileExtent)

    val extracted = vt2.layers("test").features.head.mapGeom(_.reproject(WebMercator, LatLng))

    // failure
    extracted.geom should equal(p)
  }

```

**Closed** 2019-09-07 02:44 UTC
