### ISSUE TITLE
`scala.MatchError: (53971,53970)` in `TiffTagsReader.scala`

### ISSUE THREAD

**Issue by yoninachmany** [locationtech/geotrellis#2268] opened 2017-06-29 14:25 UTC
```
scala> val tags = TiffTagsReader.read("../../Downloads/013022223121.tif")
scala.MatchError: (53971,53970) (of class scala.Tuple2$mcII$sp)
  at geotrellis.raster.io.geotiff.reader.TiffTagsReader$.readTag(TiffTagsReader.scala:112)
  at geotrellis.raster.io.geotiff.reader.TiffTagsReader$.read(TiffTagsReader.scala:100)
  at geotrellis.raster.io.geotiff.reader.TiffTagsReader$.read(TiffTagsReader.scala:49)
  at geotrellis.raster.io.geotiff.reader.TiffTagsReader$.read(TiffTagsReader.scala:33)
  ... 42 elided
scala> 
```

(tagMetadata.tag, tagMetadata.fieldType) match fails: https://github.com/locationtech/geotrellis/blob/master/raster/src/main/scala/geotrellis/raster/io/geotiff/reader/TiffTagsReader.scala#L112

tagMetadata.tag != codes.TagCodes.GeoKeyDirectoryTag: https://github.com/locationtech/geotrellis/blob/master/raster/src/main/scala/geotrellis/raster/io/geotiff/reader/TiffTagsReader.scala#L100

 codes 53971,53970 do not appear in TagCodes: https://github.com/locationtech/geotrellis/blob/master/raster/src/main/scala/geotrellis/raster/io/geotiff/tags/codes/TagCodes.scala

can't attach tiff here, but i can send over if asked

**Comment by yoninachmany** [comment] 2017-06-29 15:33
Blocking ingest of SpaceNet data for demo notebook https://github.com/locationtech-labs/geopyspark/blob/spacenet-notebook/docker/notebooks/SpaceNet%20demo.ipynb

**Comment by jbouffard** [comment] 2017-06-30 17:27
This issue is caused by an error that occurs when using the `getSignedByteArray` method to read in the tags. The error being that the `byteReader` does not have its original position reset after the data has been read ([link](https://github.com/locationtech/geotrellis/blob/master/raster/src/main/scala/geotrellis/raster/io/geotiff/util/ByteReaderExtensions.scala#L198)). Thus, when the next tag is being read, it gets some bad value (hence the `(53971,53970)`) which triggers the `scala.MatchError`.

The reason why this wasn't caught sooner is because `getSignedByteArray` is only used to read [unstandardized tags](https://github.com/locationtech/geotrellis/blob/master/raster/src/main/scala/geotrellis/raster/io/geotiff/tags/JpegTags.scala#L23) or the [`JpegTables` tag](https://github.com/locationtech/geotrellis/blob/master/raster/src/main/scala/geotrellis/raster/io/geotiff/reader/TiffTagsReader.scala#L589), and neither are that common. With your situation being the latter of the two.

PR #2270 resolves this, and once it's merged, you shouldn't have any more issues.

**Closed** 2017-06-30 19:03 UTC

**Comment by yoninachmany** [comment] 2017-07-03 14:36
Thanks @jbouffard and @pomadchin!
