### ISSUE TITLE
Unexpected Viewshed results

### ISSUE THREAD

**Issue by bespin1** [locationtech/geotrellis#2910] opened 2019-04-24 22:11 UTC
I'm getting unexpected viewshed results.

1. Results are missing land surface that are clearly visible, only flat ocean area is tagged as visible
2. Results are short of the maxDistance=3218.69
3. There's a repeating, no data, pattern in the visible ocean area
![gt_viewshed2](https://user-images.githubusercontent.com/8809541/56697001-6367e880-66a2-11e9-8fc2-2403a334ecd2.png)

```
val point15 = Viewpoint(x = 370815.36, y = 3734806.85, viewHeight = 1.8, angle = 0, fieldOfView = 360, altitude = 0)
val layerVs: TileLayerRDD[SpatialKey] = layerRdd.viewshed(Seq(point15), maxDistance=3218.69, curvature=true)
```

**Comment by jpolchlo** [comment] 2019-04-25 12:38
Seems like @jamesmcclain should have some insight on this.  ¿Señor?

**Comment by pomadchin** [comment] 2019-04-25 12:44
@jpolchlo sounds about right, marked it as `bug` for now.

**Comment by jamesmcclain** [comment] 2019-04-25 13:06
I think that `altitude` [should most likely be -∞](https://github.com/locationtech/geotrellis/blob/master/spark/src/main/scala/geotrellis/spark/viewshed/IterativeViewshed.scala#L45) (that is the default value).  Setting it to zero is asking the question "is the point zero meters above sea level is visible at this x and y given this terrain?".  (Sorry if that is confusing, but we that is there to allow queries in the air [for tracking objects in the air from the ground]).

If that does not work, I would try toggling `curvature` on and off (but still leave `altitude` as  -∞).

If that does not work, I would try increasing `viewHeight` until you see something more reasonable (but still leave `altitude` as  -∞), then comparing it to GRASS.  If the outputs are still significantly different, then there is definitely a bug that needs to be addressed.

**Comment by bespin1** [comment] 2019-04-25 18:50
Ok, that makes sense, I knew it was user error. The below example produces results very similar to GRASS now. Still having problems with 2 and 3 though, any idea?

1. ~~Results are missing land surface that are clearly visible, only flat ocean area is tagged as visible~~
2. Results are short of the maxDistance=3218.69
3. There's a repeating, no data, pattern in the visible ocean area

```
val point27 = Viewpoint(x = 370815.36, y = 3734806.85, viewHeight = 1.8, angle = 0, fieldOfView = 360, altitude = -1.0/0)
val layerVs: TileLayerRDD[SpatialKey] = layerRdd.viewshed(Seq(point27), maxDistance=3218.69, curvature=true) 
```
![gt_viewshed3](https://user-images.githubusercontent.com/8809541/56760329-cebbc400-674f-11e9-808c-fc6348895819.png)

**Comment by bespin1** [comment] 2019-04-25 18:55
Accidentally closed, still need to figure out questions 2 and 3.

**Comment by jamesmcclain** [comment] 2019-04-25 19:11
**3** Is probably a result of numerical imprecision and we would need to do some work to resolve those (I think that those `nodata`s are just pixels that are being reported as not visible).  GRASS is most likely using a more sophisticated algorithm and/or sampling the function in a more sophisticated way.  Please let us know if you need a more exact calculation.

**2** Is most likely due to imprecision in computing the number of meters per pixel at that particular location (assuming that GRASS is correct and GeoTrellis is not).  I suspect that if you were to perform that exact experiment near a pole then again at the equator, the differences in the radii would be different .  Please let us know if you need a more exact calculation.

**Comment by bespin1** [comment] 2019-04-26 18:42
> Please let us know if you need a more exact calculation

Right now I'm just at the hello world phase and assessing GT. I think both results are pretty unexpected though. The distance estimation is pretty far off; it's especially weird because the map units are already in meters.  The no data pixel pattern is odd as well, makes it look more like an estimate and less of a solid R2.  In my use case I plan to use the viewshed as a mask to see what kinds of things are visible.   Missing pixels isn't likely to impact that very much.

**Comment by jamesmcclain** [comment] 2019-04-26 19:07
Can you send us data to reproduce your problems?

**Comment by bespin1** [comment] 2019-04-26 21:05
[Here's the elevation tif.  ](https://www.dropbox.com/s/eur5pljxgzo867f/elev_with_buildings2_clipped2.tar.gz?dl=0)

Note they the buildings are faked, I only had vector boundaries so I just converted them to raster and assigned a height of 5 meters, then dropped that on top of the dem.

**Comment by jamesmcclain** [comment] 2019-04-28 01:15
Okay, thanks.  I am not on the GeoTrellis team anymore, but I will take a look at this.  I will try to either take care of it myself or get it on their list.

**Comment by jamesmcclain** [comment] 2019-05-06 14:06
Sorry for the delay, I hope to have some fixes for this shortly.

**Comment by jamesmcclain** [comment] 2019-05-08 16:31
@bespin1 Thank you very much for your bug report.  I have attempted to address the issues that you helpfully pointed out.

**Closed** 2019-05-08 20:04 UTC
Labels: bug
